language: node_js
node_js:
  - "stable"
  - "4.1"
  - "4.0"
env:
  global:
  - secure: "j+5gVhwZLf6koGyYmvm38u/7BRpMzI6XHF76Iu37PRXhrL59KymBgpEfq9TpVXIh/fuwJqv1rtQMXsWL9Vk+CH2QhAjXstSoHtnUOE0Fw5VTT1HVhZawoEXYHGRwnKY4LeZkhJS5B94k7GFoSgf0tmjRZPJYkElKbHqPsQdxaKkQ5kpv/ECgF4QMv95hnVzbuX220HMLfCdRD9loUw8G39kAJjT3F+DH+wzEOaLCo2gRWayaevnJklrAXc82m09UXYB4bKofUBt7IYEdE68ycCeIKcIOU25Yi06SQuFkKItXdRcH8XbDcvFbPoC6g3TIIVZ68xQVqaliNrgDYWkFJmwl7kWdWma3p36a0s0nX5QkyOcecQt9HkUzhHbAXE8KyDOKFQchwGoK7uFYIVr8zTwJzojqmOBOGcJQ57Prf94ktyIe6ifgr6Bd3XCeCn35dWtUhY2F9cu6Sgo0rWcPGmvgmeZS89CnvKqnrGJqYsAjM13qVnGllvglr+eKEf+q86qlOO6lSaz4cm3GHeP+WL9zcdxtl5V5mmSntn18xZbL7w2kKLrAVZMtBN7R01afOBz7gnY29fGrojJI/j4fqCOVBZ6icbYlH4TcEcDBLz3Qfa85VIydBbdLelDY7pssUbYq0fkyZ3SdBdxLfj6ao8Kr5UvExO7CXttlbU2heE0="
